### ISSUE TITLE
Cannot set break point if placed in /modules

### ISSUE THREAD

**Issue by thdoan** [sholsinger/demandware-template-debugger#1]
After following the alternative scenario of placing the script in /modules, I am not able to set a break point as that option is disabled:

![image](https://user-images.githubusercontent.com/4110567/83186569-90769e00-a0e1-11ea-8c88-8fa4582e4d0f.png)

Does `modules` have to be created as a new cartridge?

**Comment by sholsinger** [comment]
@thdoan What editor were you using when this occurred?
